# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: EDUCEN
description: Handbook on Culture and Urban Disaster
url: http://educen.cultureanddisaster.eu/

title: EDUCEN
email: jeroen.warner@wur.nl
url: http://educen.cultureanddisaster.eu/
description: Handbook on Culture and Urban Disaster
twitter:
  username: EDUCEN_EU
logo: /img/logo.png

gems:
  - jekyll-seo-tag

sass:
  sass_dir: _sass

collections:
  sections:
  chapters:
    output: true
    permalink: handbook/:title
  tools:
    output: true
    permalink: :title
  case-studies:
    output: true
  toolkit: 
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner.jpg
# Build settings
markdown: kramdown
exclude: [vendor]
